### ISSUE TITLE
AjaxAppender error handling

### ISSUE THREAD

**Issue by HarryBurns** [mperdeck/jsnlog.js#11]
Hi Matt!

I'm using your jsnlog.js in my angular app. And it will be great to know when AjaxAppender can't send logs to server and why.

Here is [your code](https://github.com/mperdeck/jsnlog.js/blob/master/jsnlog.ts#L576):
```javascript
try {
    // .......

    // Send the json to the server.
    // Note that there is no event handling here. If the send is not
    // successful, nothing can be done about it.

    var xhr = new XMLHttpRequest();
    xhr.open('POST', ajaxUrl);

    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.setRequestHeader('JSNLog-RequestId', JL.requestId);
    xhr.send(json);
} catch (e) { }
```

There is no error handling at all!
For this problem we can add `ajaxErrorHandler` function to appender (or appender's config), and call this function every time something goes wrong. Something like:
```javascript
try{
    //...........
    var xhr = new XMLHttpRequest();
    xhr.open('POST', ajaxUrl, true); // async call is better

    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.setRequestHeader('JSNLog-RequestId', JL.requestId);

    xhr.onreadystatechange = function() {
        if (xhr.readyState != 4) return; // request is completed
        if (xhr.status != 200) {
            ajaxErrorHandler(xhr.status + ": " + xhr.statusText); // call our error handler
        }
    }

    xhr.send(json);

} catch (e) {
    ajaxErrorHandler("Fatal logger exception", e);
}
```
I wrote this code from my head and didn't test it. I just show the main idea.
Can you implement this feature please?

**Comment by mperdeck** [comment]
It is now possible to detect and handle situations where log messages cannot be sent to the server. I've written a page on this at:
http://jsnlog.com/Documentation/GetStartedLogging/HandlingLoggingFailures
