### ISSUE TITLE
XMLHttpRequest cannot load http://localhost/api/log. Request header field JSNLog-RequestId is not allowed by Access-Control-Allow-Headers.

### ISSUE THREAD

**Issue by adakumar** [mperdeck/jsnlog.js#13]
Hi All,

I am getting the below error after using the below code in my project.Could you please help out?

Error:
XMLHttpRequest cannot load http://localhost:8083/api/log. Request header field JSNLog-RequestId is not allowed by Access-Control-Allow-Headers.

Code: 
 window.onerror = function( msg, url, lineNo,errorObj) 
    { 
		 JL("onerrorLogger").fatalException({
        "msg": "Exception!", 
        "errorMsg": msg, "url": url, 
        "line number": lineNo
		}, errorObj);
		
		 
        // return true to stop error from propogating, false to allow propogation
        return true; 
    };

var appender = JL.createAjaxAppender("appender");
		var consoleAppender=JL.createConsoleAppender('consoleAppender');
		appender.setOptions({"url": "http://localhost:8083/api/log"
		});
		JL().setOptions({"requestId":"35F7446D-86F1-47FA-A9EC-547FFF510086","appenders": [appender]});

Thanks in advance

**Comment by hermanocabral** [comment]
Looks like you need to add the "JSNLog-RequestId" header to the list of allowed headers in your CORS config.

**Comment by mperdeck** [comment]
JSNLog doesn't support CORS right now. It's high on my to do list for
JSNLog, but I haven't found the time yet. Of course, if someone sent me a
pull request to make this happen, I would be most interested.

**Comment by mperdeck** [comment]
I just implemented CORS, in  the new version 2.9.0
