### ISSUE TITLE
Modifying json sent using AjaxAppender

### ISSUE THREAD

**Issue by yorraksahb** [mperdeck/jsnlog.js#15]
I wanted to update the json sent to the server, which uses Ajaxappender. Can this be done?
The main reason being i dont want to send the log level code but send the log level itself, i.e. ERROR, WARN etc.

**Comment by mperdeck** [comment]
Have a look at the beforeSend option on the AjaxAppender, as described here:
http://jsnlog.com/Documentation/JSNLogJs/AjaxAppender/SetOptions

The only other alternative would be to create your own appender, which shouldn't be too hard if you're experienced with JavaScript. To get an idea of how you'd do this, search for "AjaxAppender" in 
https://github.com/mperdeck/jsnlog.js/blob/master/jsnlog.js
or if you work in TypeScript:
https://github.com/mperdeck/jsnlog.js/blob/master/jsnlog.ts
