### ISSUE TITLE
Using in Office 365

### ISSUE THREAD

**Issue by smunir100** [mperdeck/jsnlog.js#17]
I am trying to use this in office 365 for catching fatal error and send to Azure service where log4net is configured along with jsnlog.log4net.

From the client side, console i can see -
Uncaught ReferenceError: JL is not defined

It seems that, i am missing something. Is there any sample for logging in Office 365 environment.

**Comment by mperdeck** [comment]
I'm sorry, I am completely unfamiliar with the Office 365 environment.

JL is defined in the jsnlog.js file. This contains the client side library code. Please make sure that that file is loaded - otherwise JL will not be defined. You could do that with a normal script tag (if the Office 365 environment does HTML). Also see
http://jsnlog.com/Documentation/GetStartedLogging/LoadingJsFile

**Comment by smunir100** [comment]
Hi There,
Thanks for your reply.
In Office 365, you have HTML, Javascript and CSS only. Please note that, now i am able to see the log in browser console. But my intention is to send error to WCF which is hosted in another domain. Obviously, that is blocking the request saying -Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://testiglobesvc.azurewebsites.net/jsnlog.logger. This can be fixed by moving the resource to the same domain or enabling CORS.

For 'enabling CORS', in which end (client or server) i should configure. If possible direct me to an example configuration.
Thanks in advance.

 



     On Wednesday, April 22, 2015 8:15 AM, mperdeck <notifications@github.com> wrote:
   

 I'm sorry, I am completely unfamiliar with the Office 365 environment.JL is defined in the jsnlog.js file. This contains the client side library code. Please make sure that that file is loaded - otherwise JL will not be defined. You could do that with a normal script tag (if the Office 365 environment does HTML). Also see
http://jsnlog.com/Documentation/GetStartedLogging/LoadingJsFile—

**Comment by mperdeck** [comment]
You should enable the CORS at the server end.

The jsnlog.js client side library is already CORS enabled. However, you also have to enable CORS on the server.

What happens is that the client will send a request to the server, asking it whether it is willing to accept requests from the client. The server then has to decide whether to accept this request. You'll probably want to accept requests only from domains you know - so you have to configure this in the server.

I don't know how to configure this in WCF. If you google "cors wcf" I'm sure you'll find out - many pages have been written about this.
