### ISSUE TITLE
Browserify + jsnlog

### ISSUE THREAD

**Issue by tparnell8** [mperdeck/jsnlog.js#18]
I'm trying to use JSNLog with browserify, but whenever I bundle it in, something terrible happens. 

this: `var __extends = this.__extends || `   

gets transformed into this:  `var __extends = undefined.__extends ||`  

Obviously the` undefined.__extends` is far from valid and thus throws errors.   Removing `this` seems to solve the overall issue, but I'm not sure if that is an actual valid solution. I'm using browserify with reactify, and babelify.

**Comment by mperdeck** [comment]
I can't reproduce this.

I created a new NodeJs demo that uses JSNLog on both the server and client, and that uses browserify to create a combined js file for use on the client:

https://github.com/mperdeck/jsnlog.NodeJsWorkingDemos
(open the ClientToServerSide-Browserify directory)

This worked perfectly.

Please have a look at that demo. If things go wrong in your particular use case, it would be good to send me a working sample program that reproduces the bug.

**Comment by tparnell8** [comment]
@mperdeck please take a look at this repo: https://github.com/tparnell8/jsnlogReproStep 

I believe it may be babelify aka the babel compiler

**Comment by tparnell8** [comment]
note: that is the file out of the nuget package...
