### ISSUE TITLE
babel is causing some issues

### ISSUE THREAD

**Issue by tparnell8** [mperdeck/jsnlog.js#19]
I mentioned this originally in #18 when I incorrectly blamed browserify.

it seems babel is transforming this: `var __extends = this.__extends || `   

into this:  `var __extends = undefined.__extends ||`  

Obviously the` undefined.__extends` is far from valid and thus throws errors.  

I have left a repro repo here: https://github.com/tparnell8/jsnlogReproStep you should be able to see it for yourself. I copied the js file from the nuget package...

**Comment by mperdeck** [comment]
I understand you're trying to compile jsnlog.js with Babel.

jsnlog.js is actually written in TypeScript:
https://github.com/mperdeck/jsnlog.js/blob/master/jsnlog.ts
I used the TypeScript compiler to compile jsnlog.ts to jsnlog.js (which is pure JavaScript).

Seeing that TypeScript and ES6 are pretty close, maybe running Babel against jsnlog.ts (the TypeScript code) will work.
Alternatively, you could try to modify your build script so it doesn't run Babel against jsnlog.js.
