### ISSUE TITLE
Logging uglified logs

### ISSUE THREAD

**Issue by vivekp123** [mperdeck/jsnlog.js#20]
Hello,

      I am using JSNLogger in angular app having uglification & minification done. The Logs which are getting posted to server or the stacktrace posted to server is uglified.. how can we make it readable.

Thanks,
VP

**Comment by mperdeck** [comment]
Apologies for the late reply. I'm not sure what you mean when you say that the logs or stack trace are uglified. Any log information is created by you. The stack trace will indeed refer to the uglified code, but I'm not sure how JSNLog could change that. 

Note that when handling an uncaught exception, Chrome and the latest IE will give you both the line number and the column where the exception happened, which should make working with uglified code a bit easier:
http://jsnlog.com/Documentation/GetStartedLogging/ExceptionLogging
