### ISSUE TITLE
Issue in compiled JS

### ISSUE THREAD

**Issue by shotmonkey** [mperdeck/jsnlog.js#27]
Hello,

2.17.0 seems to have reverted some previous changes (made just hours before) to the javascript file, specifically in how __extends is defined.

This is a breaking issue when used via babel in some environments, as `this.__extends` is replaced with `undefined.__extends`

I suspect it is a typescript compiler version issue, as compiling this locally with the latest compiler produces the earlier version.

Relevant lines:

2.17.0: https://github.com/mperdeck/jsnlog.js/commit/3853663ff33da8fb4618ce49fd168ba41d5f9cf4
`var __extends = this.__extends || function (d, b) {`
Earlier commit: https://github.com/mperdeck/jsnlog.js/commit/02368818ff56e486651297d980b8ce917596e762
`var __extends = (this && this.__extends) || function (d, b) {`

**Comment by jFensch** [comment]
I am currently affected my this issue.  Has there been any progress in resolving?

**Comment by shotmonkey** [comment]
I ended up forking, recompiling (after removing IE8-specific behaviour which TypeScript doesn't officially support any more) and using that.

**Comment by mperdeck** [comment]
I fixed the issue in my build system, and released the (correctly) recompiled files as part of the latest release, 2.17.3.
