### ISSUE TITLE
Updated TypeDefinitions

### ISSUE THREAD

**Issue by jFensch** [mperdeck/jsnlog.js#28]
Its appears the definitions on DefinitelyTyped are stale.

Is there a possibility to have these just included in the NPM package using the appropriate "typings" config: [link](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html)?

**Comment by mperdeck** [comment]
Thanks for your suggestion. I've included the typing config and released that (version 2.17.3). Also sent pull request to DefinitelyTyped to bring definitions up to date.

**Comment by jFensch** [comment]
After the update I get the following:

File '../node_modules/jsnlog/Definitions/jsnlog.d.ts' is not a module.

Exported external package typings file '../node_modules/jsnlog/Definitions/jsnlog.d.ts' is not a module. Please contact the package author to update the package definition.

**Comment by mperdeck** [comment]
I need more detail in order to reproduce this. Specifically which commands etc. do you use when you get this error?

**Comment by jFensch** [comment]
Smallest test to reproduce here by executing **_npm install_** and then **_npm run test_** on the following repo:

https://github.com/jFensch/jsnlog-example

**Comment by mperdeck** [comment]
Thanks for the test code. I fixed the problem and released the fix as version 2.17.4.
