### ISSUE TITLE
Is there a way to have <script src='jsnlog.min.js' /> before the initialization script

### ISSUE THREAD

**Issue by kinau** [mperdeck/jsnlog.js#31]
I use jsnlog in one of my ASP.NET MVC5 projects. I use the @Html.Raw(JSNLog.JavascriptionLogging.Configure()) at the top of my layout page. It keeps errorring during page load complaining about: 

0x800a1391 - JavaScript runtime error: 'JL' is undefined

Script on HTML

<script type="text/javascript">
//<![CDATA[
var __jsnlog_configure = function (JL) {
JL.setOptions({"clientIP": "127.0.0.1",
"requestId": "80001b18-0004-fe00-b63f-84710c7967bb",
"enabled": true,
"maxMessages": 2147483647});
var logger0=JL();
logger0.setOptions({"onceOnly": [],
"level": 1000});
}; try { __jsnlog_configure(JL); } catch(e) {};
//]]>
</script>
<script type="text/javascript" src="/Scripts/jsnlog.min.js"></script>

If I include the jsnlog.min.js at the top like below, it works but jsnlog.min.js will be loaded twice. Please advice. Thanks.

<script src="~/Scripts/jsnlog.min.js"></script>
@Html.Raw(JSNLog.JavascriptLogging.Configure())

**Comment by mperdeck** [comment]
From your description, I can only assume that your pages run JavaScript code that tries to log something before you call @Html.Raw(JSNLog.JavascriptionLogging.Configure())

Your bug report doesn't have enough information to reproduce the problem. If the problem persists, could you please create a small test application that reproduces the problem and let me know where to find it on Github. I can then reproduce the issue at my end and come up with a solution.
