### ISSUE TITLE
RequestId not sent in header

### ISSUE THREAD

**Issue by Payetus** [mperdeck/jsnlog.js#41]
Adding the RequestId in the options:

```
JL().setOptions({
        "requestId": "35F7416D-86F1-47FA-A9EC-547FFF510086",
        "appenders": [this.appender]
    });
```
Does not send the requestId in the header of the http Request:
![image](https://cloud.githubusercontent.com/assets/3797659/25655010/a63dc856-2ff3-11e7-9a5e-e7a04a1ac10d.png)

**Comment by mperdeck** [comment]
This happens because you set the requestId on the nameless logger, instead of the library itself.
Use JL.setOptions(.. instead of JL().setOptions(....
(no brackets after the JL)

See
http://jsnlog.com/Documentation/JSNLogJs/JL/SetOptions
