### ISSUE TITLE
error TS1127: Invalid character

### ISSUE THREAD

**Issue by ndevnani** [mperdeck/jsnlog.js#45]
Hi,

I installed jsnlog for node js  + angular 4 env, and when I imported the log like this in my code:

import { JL } from 'jsnlog';

and compiled, I got bunch of errors like these:

ERROR in ...\node_modules\jsnlog\Definitions\jl.d.ts
(1,1): error TS1127: Invalid character.

To fix it, I updated the jl.d.ts file and removed first few lines of comments, and the code compiled. I presume there is some invalid unicode in the file (I am using Windows 10), which caused the issue.

Thanks

**Comment by mperdeck** [comment]
This has now been fixed in release 2.24.1 (just gone live).
