### ISSUE TITLE
onunhandledrejection handler should log error explicit otherwise it doesn't show on console

### ISSUE THREAD

**Issue by neooleg** [mperdeck/jsnlog.js#47]
## Issue

- Based on MDN there is no info about return for onunhandledrejection
- Probably because of this any exception from promise doesn't show within browser console! **It looks dangerous because it might lead to confuse on debug assuming there is no error, but they just not showing**

## Solution

Hence, it seems code for this handler https://github.com/mperdeck/jsnlog.js/issues/35 should be extended with explicit error logging to show error anyway.

**Comment by mperdeck** [comment]
Yes, that is a good point. I'll consider it for the next release.

Meanwhile, you can these errors shown in the browser console already by using a console appender: 
http://js.jsnlog.com/Documentation/JSNLogJs/ConsoleAppender

**Comment by neooleg** [comment]
@mperdeck you closed the issue, however, there is no any commits for this.

Do you have any ETA for the next release?

**Comment by neooleg** [comment]
Updated Solution in the initial message and sent a PR

**Comment by mperdeck** [comment]
This has now been released (version 2.24.2).
