### ISSUE TITLE
JavaScript Error Handling mechanism should cache errors if offline and deliver as soon as client online

### ISSUE THREAD

**Issue by neooleg** [mperdeck/jsnlog.js#49]
## Issue

There is greate feature [Javascript Error Handling](http://jsnlog.com/Documentation/HowTo/JavascriptErrorHandling) which automatically catch unhandled errors.

However, the error is lost if user become offline and appeared online even for few seconds.

## Solution
The logger should cache errors in offline (or if sending failed) and send them as soon as client become online.

**Comment by mperdeck** [comment]
Thanks for your suggestion! I implemented this in version 2.25.0. See
http://jsnlog.com/Documentation/HowTo/HandlingLostConnection

**Comment by neooleg** [comment]
Does it use localstorage in case if page will be "refreshed"?

**Comment by mperdeck** [comment]
No it doesn't. So yes, if the user refreshes the page, the log entries are lost. Thanks for pointing this out. I'll add this to the to-do list.
