### ISSUE TITLE
missing jsnlog_interfaces.d.ts

### ISSUE THREAD

**Issue by pid27** [mperdeck/jsnlog.js#52]
jsnlog.js keeps looking for this file. 
It doesnt get downloaded from nuget.
 
<reference path="Definitions/jsnlog_interfaces.d.ts"/> 

Do i need to remove this line ?

**Comment by mperdeck** [comment]
Yes, you can remove that line. I've changed the build process to remove that line, so future versions of jsnlog.js won't have it anymore. Thanks for the heads up.
