### ISSUE TITLE
"TypeError: jsnlog_1.JL is not a function" with TypeScript and SystemJS

### ISSUE THREAD

**Issue by icnocop** [mperdeck/jsnlog.js#56]
Hi.

Thank you for jsnlog.js.

I'm trying to integrate jsnlog.js using TypeScript and SystemJS, similar to issue https://github.com/mperdeck/jsnlog.js/issues/24, but it happens with JSNLog 2.25.1.

I've attached a sample Visual Studio solution [here](https://github.com/mperdeck/jsnlog.js/files/1555254/jsnLogWebApplication.zip).

Basically, this causes the JavaScript run-time error `TypeError: jsnlog_1.JL is not a function` in chrome:
```
import { JL } from "jsnlog";

JL().debug("Hello world");
```

But I'm able to work-around this issue using:
```
declare var JL;
import "jsnlog";

JL().debug("Hello world");
```

But then I lose typing.

Any thoughts?

Thank you!

**Comment by mperdeck** [comment]
Sorry for the late response.

I have no experience with SystemJS and have no idea what is going wrong.

Should you find out and if it is an issue in jsnlog.js, I would be interested in a pull request.

**Comment by icnocop** [comment]
To get typings, instead of this:
```
/// <reference types="jsnlog" />
import "jsnlog";
declare var JL;
```

I had to use this:
```
/// <reference path="../node_modules/jsnlog/Definitions/jl.d.ts" />
import { JL } from "jsnlog";
```

References:
https://stackoverflow.com/questions/35252939/howto-import-jsnlog-module-using-typescript-systemjs-jspm
https://github.com/Microsoft/TypeScript/issues/2262

**Comment by icnocop** [comment]
It seems jsnlog.sln requires Visual Studio 2013.

When I build jsnlog.sln in Visual Studio 2015, I get different results than what's in git.
Most importantly is the jsnlog.js.map file is not re-generated based on my code changes.

I did notice files referenced in jsnlog.sln are missing from git:
.\Definitions\generate.bat
.\Definitions\jsnlog.DefinitelyTypedHeading.txt
.\Definitions\jsnlog.DefinitelyTypedHeading.txt.template
.\Definitions\jsnlog.jl.d.ts

I'm using the master branch.

Is there a contributing guide? (ex. CONTRIBUTING.md)

Thank you.

**Comment by mperdeck** [comment]
Thanks for pointing out how to make jsnlog.js work with SystemJs. I'll update the jsnlog.ts and the web site for the next release.

You're right, the .sln file had lots of broken file references. Fixed those now. I use Visual Studio 2017 Community Edition to open that file.

You can find the Google Closure Compiler at
https://github.com/google/closure-compiler

As you found out, the minify.bat / minify.ps1 files were never meant for use by people other than myself. It is part of the build process to create new releases of JSNLog (JavaScript file, Nuget package, website, etc.) It heavily ties in with the other JSNLog related projects. I've now added some comments to that effect.

As far as jsnlog.js is concerned, this simply generates a copyright message with the correct version number, etc. If you want to use your own version of jsnlog.js, you should be fine with just using the TypeScript compiler and a minifier.

No, there is no contributing guide. I am more than happy to receive bug reports and pull requests, but never saw the need for a contributing guide.

**Comment by Brandinga** [comment]
FYI

this fixes also this one: [Angular aot build](https://github.com/mperdeck/jsnlog.js/issues/46)
