### ISSUE TITLE
A way to remove JSNLog-RequestId header

### ISSUE THREAD

**Issue by HariAlexiev** [mperdeck/jsnlog.js#63]
is there a way to completely remove the JSNLog-RequestId from requests ?
I'm behind gateway which is rejecting me, because of not approve headers... and there is no way to change the gateway...

Failed to load https://gateway/log-collector: Request header field JSNLog-RequestId is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by mperdeck** [comment]
I'm sorry, there is no way at the moment to switch it off.
